version: '3'

services:
  redis-server:
    image: 'redis'
  node-app:
    restart: unless-stopped
    # Look in the current dir for a Dockerfile and use it to build a container
    build: .
    ports:
      - "4001:8081"
